//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcademicYear
    {
        public AcademicYear()
        {
            this.Marks = new HashSet<Mark>();
            this.PromotionHistories = new HashSet<PromotionHistory>();
            this.StudentClassSections = new HashSet<StudentClassSection>();
            this.TempPromotionTables = new HashSet<TempPromotionTable>();
        }
    
        public int YearId { get; set; }
        public string Year { get; set; }
        public bool IsCurrent { get; set; }
    
        public virtual ICollection<Mark> Marks { get; set; }
        public virtual ICollection<PromotionHistory> PromotionHistories { get; set; }
        public virtual ICollection<StudentClassSection> StudentClassSections { get; set; }
        public virtual ICollection<TempPromotionTable> TempPromotionTables { get; set; }
    }
}
