//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public long AttendanceId { get; set; }
        public System.DateTime Date { get; set; }
        public bool IsAttend { get; set; }
        public int StudentId { get; set; }
        public int UpdatedBy { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual User User { get; set; }
    }
}
