//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassSection
    {
        public ClassSection()
        {
            this.StudentClassSections = new HashSet<StudentClassSection>();
            this.ClassSectionDayPeriodSubjects = new HashSet<ClassSectionDayPeriodSubject>();
            this.ClassSectionSubjects = new HashSet<ClassSectionSubject>();
            this.TempPromotionTables = new HashSet<TempPromotionTable>();
        }
    
        public int ClassSectionId { get; set; }
        public int ClassId { get; set; }
        public string SectionName { get; set; }
        public bool IsActive { get; set; }
        public int ClassTeacherId { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual ICollection<StudentClassSection> StudentClassSections { get; set; }
        public virtual ICollection<ClassSectionDayPeriodSubject> ClassSectionDayPeriodSubjects { get; set; }
        public virtual ICollection<ClassSectionSubject> ClassSectionSubjects { get; set; }
        public virtual ICollection<TempPromotionTable> TempPromotionTables { get; set; }
    }
}
