//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassSectionSubject
    {
        public ClassSectionSubject()
        {
            this.ClassSectionSubjectTeachers = new HashSet<ClassSectionSubjectTeacher>();
            this.Marks = new HashSet<Mark>();
        }
    
        public int Id { get; set; }
        public int ClassSectionId { get; set; }
        public int SubjectId { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ClassSection ClassSection { get; set; }
        public virtual ICollection<ClassSectionSubjectTeacher> ClassSectionSubjectTeachers { get; set; }
        public virtual ICollection<Mark> Marks { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
