//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Day
    {
        public Day()
        {
            this.ClassSectionDayPeriodSubjects = new HashSet<ClassSectionDayPeriodSubject>();
        }
    
        public int DayId { get; set; }
        public string DayName { get; set; }
        public bool IsOffDay { get; set; }
    
        public virtual ICollection<ClassSectionDayPeriodSubject> ClassSectionDayPeriodSubjects { get; set; }
    }
}
