//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Admins = new HashSet<Admin>();
            this.Staffs = new HashSet<Staff>();
            this.Teachers = new HashSet<Teacher>();
        }
    
        public int EmployeeId { get; set; }
        public System.DateTime JoinDate { get; set; }
        public string Phone { get; set; }
        public bool IsActive { get; set; }
        public int PersonId { get; set; }
        public string IdNumber { get; set; }
    
        public virtual ICollection<Admin> Admins { get; set; }
        public virtual Person Person { get; set; }
        public virtual ICollection<Staff> Staffs { get; set; }
        public virtual ICollection<Teacher> Teachers { get; set; }
    }
}
