//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Period
    {
        public Period()
        {
            this.ClassSectionDayPeriodSubjects = new HashSet<ClassSectionDayPeriodSubject>();
        }
    
        public int PeriodId { get; set; }
        public string PeriodName { get; set; }
        public System.TimeSpan TimeFrom { get; set; }
        public System.TimeSpan TimeTo { get; set; }
    
        public virtual ICollection<ClassSectionDayPeriodSubject> ClassSectionDayPeriodSubjects { get; set; }
    }
}
