//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionHistory
    {
        public int PromotionId { get; set; }
        public int StudentId { get; set; }
        public int PreviousClassId { get; set; }
        public Nullable<int> CurrentClassId { get; set; }
        public string Remarks { get; set; }
        public int PreviousYearId { get; set; }
        public int UpdatedBy { get; set; }
    
        public virtual AcademicYear AcademicYear { get; set; }
        public virtual Class Class { get; set; }
        public virtual Class Class1 { get; set; }
        public virtual Student Student { get; set; }
        public virtual User User { get; set; }
    }
}
