//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Attendances = new HashSet<Attendance>();
            this.Marks = new HashSet<Mark>();
            this.PromotionHistories = new HashSet<PromotionHistory>();
            this.StudentClassSections = new HashSet<StudentClassSection>();
            this.TempPromotionTables = new HashSet<TempPromotionTable>();
        }
    
        public int StudentId { get; set; }
        public int PersonId { get; set; }
        public bool IsActive { get; set; }
        public string IdNumber { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string FatherProfession { get; set; }
        public string MotherProfession { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
    
        public virtual ICollection<Attendance> Attendances { get; set; }
        public virtual ICollection<Mark> Marks { get; set; }
        public virtual Person Person { get; set; }
        public virtual ICollection<PromotionHistory> PromotionHistories { get; set; }
        public virtual ICollection<StudentClassSection> StudentClassSections { get; set; }
        public virtual ICollection<TempPromotionTable> TempPromotionTables { get; set; }
    }
}
