//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempPromotionTable
    {
        public int Id { get; set; }
        public int StudentId { get; set; }
        public bool IsPassed { get; set; }
        public Nullable<int> NextClassSectionId { get; set; }
        public int CurrentYearId { get; set; }
        public double AverageMarks { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> NextClassId { get; set; }
    
        public virtual AcademicYear AcademicYear { get; set; }
        public virtual Class Class { get; set; }
        public virtual ClassSection ClassSection { get; set; }
        public virtual Student Student { get; set; }
    }
}
