//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Admins = new HashSet<Admin>();
            this.Attendances = new HashSet<Attendance>();
            this.Marks = new HashSet<Mark>();
            this.People = new HashSet<Person>();
            this.PromotionHistories = new HashSet<PromotionHistory>();
            this.Staffs = new HashSet<Staff>();
        }
    
        public int UserId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public int UserTypeId { get; set; }
    
        public virtual ICollection<Admin> Admins { get; set; }
        public virtual ICollection<Attendance> Attendances { get; set; }
        public virtual BaseData BaseData { get; set; }
        public virtual ICollection<Mark> Marks { get; set; }
        public virtual ICollection<Person> People { get; set; }
        public virtual ICollection<PromotionHistory> PromotionHistories { get; set; }
        public virtual ICollection<Staff> Staffs { get; set; }
    }
}
